### ISSUE TITLE
Crash on latest version

### ISSUE THREAD

**Issue by Matthysse** [Poulpynou/dawnoftimebuilder#48] opened 2024-05-31 19:58 UTC
Hello !

Using the latest version of the mod (1.5.7) makes my modpack crash. The version before does not. 
Here is the debug.log: [https://mclo.gs/ehQ1wiV](https://mclo.gs/ehQ1wiV), and the crash-report: [https://pastebin.com/bUvSM3bF](https://pastebin.com/bUvSM3bF).

**Comment by PierreChag** [comment] 2024-05-31 20:19
Hello and thank you for the report !
I changed the way we handle the hitbox of blocks. I'm working on a fix :)

**Comment by PierreChag** [comment] 2024-06-02 14:11
Hello !
After some exploration, the problem comes from the mod Every Compat (Wood Good). I changed the way I create some blocks, and since they add variants of our blocks in  every woods, they need to update their code first.

I contacted the owner of this mod and they are working on it.
I will keep this issue open until the problem is fixed :)

Until then, both mods are not compatibles saddly...

**Comment by PierreChag** [comment] 2024-06-03 09:25
Hello !
Every Compat released a new version that is compatible. You should be able to play with your modpack.
FYI, DoTBE is still not compatible with Dramatic Doors.

Can you confirm it works ?

**Comment by Matthysse** [comment] 2024-06-04 17:39
I confirm it now works

**Comment by PierreChag** [comment] 2024-06-04 17:41
Great ! I close the issue !

**Closed as completed by PierreChag** 2024-06-04 17:41 UTC
Labels: bug, compatibility, 1.20.1
